FROM debian:stretch-slim as builder-protoserver-go

# The default repos in the stretch-slim image stopped working consistently for some reason so overwrite 'em...
#RUN echo "deb http://ftp.us.debian.org/debian/ stretch main contrib non-free" > /etc/apt/sources.list
#RUN echo "deb-src http://ftp.us.debian.org/debian/ stretch main contrib non-free" >> /etc/apt/sources.list

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -qq -y install apt-utils wget libc-dev git gcc vim net-tools
RUN apt-get -y clean

RUN wget --quiet https://dl.google.com/go/go1.15.3.linux-amd64.tar.gz
RUN tar -xf go1.15.3.linux-amd64.tar.gz -C /usr/local
RUN rm go1.15.3.linux-amd64.tar.gz
RUN mkdir /go

## Set up the project directory and go pathing
ENV GOROOT=/usr/local/go
ENV GOPATH=/go
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH
RUN go version

## Install delve debugger
RUN go get -u github.com/derekparker/delve/cmd/dlv

## Set working directory
WORKDIR /opt

## This stops the unit tests from looking for a config file when we build the go application
ENV PROTOSERVER_LOG_TYPE='stderr'
ENV PROTOSERVER_LOG_LEVEL='debug'

## Copy and run the magic build script
CMD ["kube/containerFiles/kube-build.sh"]
