// Code generated by github.com/kyledinh/btk-cli-go (btk-cli) version 0.0.6-8c12189-dirty
// DO NOT EDIT. Edit in ./spec/jwt-tokens.latest.yaml 1.0.0 then rerun generator.

package model

import (
	_ "github.com/pkg/errors"
)

type User struct {
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Password  string `json:"password"`
}
